#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
"""
Initially Generated By:
    python -m utool --tf setup_repo --repo=ibeis-flukematch-module --codedir=~/code --modname=ibeis_flukematch
"""
from __future__ import absolute_import, division, print_function, unicode_literals


def ibeis_flukematch_main():
    ignore_prefix = []
    ignore_suffix = []
    import utool as ut
    # allows for --tf
    ut.main_function_tester('ibeis_flukematch', ignore_prefix, ignore_suffix)

if __name__ == '__main__':
    """
    Usage:
        python -m ibeis_flukematch --tf <funcname>
    """
    print('Running ibeis_flukematch main')
    ibeis_flukematch_main()
